# NOTE:
#   This script uses the node's hostPath for sharing blobs, instead of the reocmmended NFS.
#
# PREPARATION:
#  - On K8s node: mkdir -m 777 ${_SHARE_DIR%/}/${_ID}
#  - Also, copy the 'sonatype-license.lic' into ${_SHARE_DIR%/}, with the read permission.
#  - On PostgreSQL server: . ./utils.sh && _postgresql_create_dbuser "${_ID}"
#  - _DNS is my hack, and usually wouldn't need to use this.
#
# kubectl create namespace "sonatype"
# export _ID="nxrm3pg" _DNS="192.168.52.31" _SHARE_DIR="/var/tmp/share" # NOTE: can't use "-" for _DB_USER
# export _TAG="3.33.1" _DB_USER="${_ID}" _DB_PWD="${_ID}" _JDBC_URL="jdbc:postgresql://192.168.52.31:5432/${_ID}"
# eval 'echo \"\\$\\(cat ./k8s-nxrm3-pg.yaml\\)\"' > /tmp/${_ID}.yaml # Replace single quotes with double quotes and remove \\
# kubectl apply -n "sonatype" -f /tmp/${_ID}.yaml
#
# POST DEPLOY:
#   Do not forget to configure Ingress.
#   To test:
#   To recreate, 'kubectl delete -n sonatype -f /tmp/k8s-nxrm3-pg.yaml',
#     and etc/fabric/nexus-store.properties if JDBC setting was changed.
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nxrm3-pg-data-pvc
  labels:
    app: nxrm3-pg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  #storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxrm3-pg-deployment
  labels:
    app: nxrm3-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxrm3-pg
  template:
    metadata:
      labels:
        app: nxrm3-pg
    spec:
      terminationGracePeriodSeconds: 120
      # NOTE: Without initContainers, it fails to start on Docker-Desktop
      initContainers:
        - name: my-customizaion
          env:
            - name: BLOBS_PATH
              value: /var/tmp/share/sonatype/${_ID}/blobs
            - name: NAMESERVER
              value: ${_DNS:-127.0.0.1}
          image: busybox:1.33.1
          #[ -d /nexus-data/blobs ] && [ ! -L /nexus-data/blobs ] && mv -v /nexus-data/blobs /nexus-data/blobs_orig;
          # Below echo nameserver ... is my personal hack as i do not want to use coreDNS
          command: ['sh', '-c', 'echo nameserver \$NAMESERVER > /etc/resolv.conf;mkdir -p -m 777 -v \$BLOBS_PATH;[ ! -L /nexus-data/blobs ] && ln -v -s \$BLOBS_PATH /nexus-data/blobs;chown -v -R 1000:1000 /nexus-data;']
          volumeMounts:
            - name: nexus-data-volume
              mountPath: /nexus-data
            - name: nexus-share-volume
              mountPath: /var/tmp/share
      containers:
        - name: nxrm3-pg-pod
          securityContext:
            # TODO: should I use 200?
            runAsUser: 1000
          image: sonatype/nexus3:${_TAG:-latest}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: 'false'
            - name: INSTALL4J_ADD_VM_PARAMS
              # No schema specified, so will be public.
              value: '-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m \
                -Djava.util.prefs.userRoot=/nexus-data/javaprefs \
                -Dnexus.licenseFile=/var/tmp/share/sonatype/sonatype-license.lic \
                -Dnexus.datastore.enabled=true \
                -Dnexus.datastore.nexus.name=nexus \
                -Dnexus.datastore.nexus.type=jdbc \
                -Dnexus.datastore.nexus.jdbcUrl=${_JDBC_URL} \
                -Dnexus.datastore.nexus.username=${_DB_USER} \
                -Dnexus.datastore.nexus.password=${_DB_PWD} \
                -Dnexus.datastore.nexus.maximumPoolSize=10'
          volumeMounts:
            - name: nexus-data-volume
              mountPath: /nexus-data
            - name: nexus-share-volume
              mountPath: /var/tmp/share
      volumes:
        - name: nexus-data-volume
          persistentVolumeClaim:
            claimName: nxrm3-pg-data-pvc
        - name: nexus-share-volume
          hostPath:
            path: ${_SHARE_DIR}
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nxrm3-pg-service
  labels:
    app: nxrm3-pg
spec:
  type: NodePort
  selector:
    app: nxrm3-pg
  ports:
    - name: nexus-web-ui
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: nexus-docker-http
      protocol: TCP
      port: 4999
      targetPort: 4999
    - name: nexus-docker-https
      protocol: TCP
      port: 5000
      targetPort: 5000
