# NOTE: Copy the 'sonatype-license.lic' file under _SHARE_DIR.
#       Do not forget to configure Ingress.
#       To recreate, delete the deployment, and etc/fabric/nexus-store.properties if JDBC setting was changed.
#export _DB_USER="nxrm3" _DB_PWD="nxrm3" _JDBC_URL="jdbc:postgresql://192.168.52.31:5432/nxrm3" _SHARE_DIR="/var/tmp/share/sonatype/k8s-nxrm3" # permission
#kubectl apply --namespace=sonatype -f <(eval "echo \"_1_cat ./k8s-nxrm3-pg.yaml_2_\"")  # Replace _1_ with a dollar sign + open brace, _2_ with close brace
apiVersion: v1
kind: Service
metadata:
  name: nxrm3-pg-service
  labels:
    app: nxrm3-pg
spec:
  type: NodePort
  selector:
    app: nxrm3-pg
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxrm3-pg-deployment
  labels:
    app: nxrm3-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxrm3-pg
  template:
    metadata:
      labels:
        app: nxrm3-pg
    spec:
      # TODO: Do I need to use initContainers to change owner of /nexus-data and serviceAccountName?
      containers:
        - name: nxrm3-pg-pod
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: 'false'
            - name: INSTALL4J_ADD_VM_PARAMS
              value: '-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m \
                -Dnexus.datastore.enabled=true -Djava.util.prefs.userRoot=/nexus-data/javaprefs \
                -Dnexus.datastore.nexus.name=nexus \
                -Dnexus.datastore.nexus.type=jdbc \
                -Dnexus.datastore.nexus.jdbcUrl=${_JDBC_URL} \
                -Dnexus.datastore.nexus.username=${_DB_USER} \
                -Dnexus.datastore.nexus.password=${_DB_PWD} \
                -Dnexus.datastore.nexus.maximumPoolSize=10 \
                -Dnexus.licenseFile=/nexus-data/sonatype-license.lic'
                # No schema specified, so will be public.
          volumeMounts:
            - name: nexus-data-volume
              mountPath: /nexus-data
      volumes:
        - name: nexus-data-volume
          hostPath:
            path: ${_SHARE_DIR}
            type: DirectoryOrCreate
