spec:
  template:
    spec:
      hostname: ${_POD_NAME}
      subdomain: pods
      dnsConfig:
        nameservers:
          - ${_DNS_SERVER}
      volumes:
        - name: nfs-volume
          nfs:
            server: ${_NFS_SERVER}
            path: ${_SHARE_DIR}
      containers:
        - name: nexus-repository-manager
          ports:
            - name: nexus-ha-5701
              protocol: TCP
              containerPort: 5701
            - name: nexus-ha-5702
              protocol: TCP
              containerPort: 5702
            - name: nexus-ha-5703
              protocol: TCP
              containerPort: 5703
            - name: nexus-ha-2424
              protocol: TCP
              containerPort: 2424
            - name: nexus-ha-2434
              protocol: TCP
              containerPort: 2434
          volumeMounts:
            - name: nfs-volume
              mountPath: /var/tmp/share/sonatype/k8s-nxrm3-ha
          lifecycle:
            postStart:
              exec:
                command: ['/bin/bash', '-c', 'curl -s -L https://raw.githubusercontent.com/hajimeo/samples/master/misc/k8s-nxrm3-ha-enable.sh --compressed | bash /dev/stdin "${_SHARE_DIR}" "${_NODE_MEMBERS}"']