# NOTE: Do not forget to configure Ingress
#       Also, export _DB_USER, _DB_PWD, _JDBC_URL, _DATA_DIR, _SHARE_DIR
apiVersion: v1
kind: Service
metadata:
  name: nxrm3-service
  labels:
    app: nxrm3
spec:
  type: NodePort
  selector:
    app: nxrm3
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxrm3-deployment
  labels:
    app: nxrm3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxrm3
  template:
    metadata:
      labels:
        app: nxrm3
    spec:
      # TODO: Do I need to use initContainers to change owner of /nexus-data and serviceAccountName?
      containers:
        - name: nxrm3-pod
          image: sonatype/nexus3:3.31.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: 'false'
            - name: INSTALL4J_ADD_VM_PARAMS
              # -Dnexus.licenseFile=/license-secret/nxrm-license.lic
              value: '-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m \
          -Dnexus.datastore.enabled=true -Djava.util.prefs.userRoot=/nexus-data/javaprefs \
          -Dnexus.datastore.nexus.name=nexus \
          -Dnexus.datastore.nexus.schema=nexus \
          -Dnexus.datastore.nexus.username=${_DB_USER} \
          -Dnexus.datastore.nexus.password=${_DB_PWD} \
          -Dnexus.datastore.nexus.type=jdbc \
          -Dnexus.datastore.nexus.jdbcUrl=${_JDBC_URL} \
          -Dnexus.datastore.nexus.advanced=maximumPoolSize\=40'
          volumeMounts:
            - name: nexus-data-volume
              mountPath: /nexus-data
            - name: share-volume
              # Using same path as the hostPath
              mountPath: ${_SHARE_DIR}
      volumes:
        - name: nexus-data-volume
          hostPath:
            path: ${_DATA_DIR}
            type: DirectoryOrCreate
        - name: share-volume
          hostPath:
            path: ${_SHARE_DIR}
            type: DirectoryOrCreate