apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nxrm
  name: ingress-nxrm
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-076c578b03aa87261, subnet-0e50f111174c8e292
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nxrm-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nxrm-service
  namespace: nxrm
  labels:
    app: nxrm
spec:
  type: NodePort
  selector:
    app: nxrm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxrm-deployment
  namespace: nxrm
  labels:
    app: nxrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxrm
  template:
    metadata:
      labels:
        app: nxrm
    spec:
      serviceAccountName: nxrm-deployment-sa
      initContainers:
        - name: chown-nexusdata-owner-to-nexus
          image: busybox:1.33.1
          command: ['chown', '-R', '200:200', '/nexus-data']
          volumeMounts:
            - name: efs-storage
              mountPath: /nexus-data
      containers:
        - name: nxrm-pod
          image: sonatype/nexus3:3.31.1
          securityContext:
            runAsUser: 200
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: "false"
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Dnexus.earlyAccess.datastore.developer=true -Dnexus.licenseFile=/license-secret/nxrm-license.lic \
          -Dnexus.datastore.enabled=true -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs \
          -Dnexus.datastore.content.name=content \
          -Dnexus.datastore.content.type=jdbc \
          -Dnexus.datastore.content.jdbcUrl={{jdbc url}} \
          -Dnexus.datastore.config.name=config \
          -Dnexus.datastore.config.type=jdbc \
          -Dnexus.datastore.config.jdbcUrl={{jdbc url}}"
          volumeMounts:
            - mountPath: /license-secret
              name: license-secret
            - name: efs-storage
              mountPath: /nexus-data
      volumes:
        - name: license-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "nxrm-license-secret"
              fsType: ext4
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim