spec:
  template:
    spec:
      hostname: ${_POD_NAME}
      subdomain: pods
      volumes:
        - name: share-volume
          hostPath:
            path: ${_SHARE_DIR}
            type: DirectoryOrCreate
      containers:
        - name: nexus-repository-manager
          ports:
            # probably don't need 5702 and 5703
            - name: nexus-ha-5701
              protocol: TCP
              containerPort: 5701
            - name: nexus-ha-2424
              protocol: TCP
              containerPort: 2424
            - name: nexus-ha-2434
              protocol: TCP
              containerPort: 2434
          volumeMounts:
            - name: share-volume
              # Currenlty always using same path
              mountPath: ${_SHARE_DIR}
          lifecycle:
            postStart:
              exec:
                # somehow when *post*Start command runs, the volume is not ready...
                command: ['/bin/bash', '-c', 'curl -s -L https://raw.githubusercontent.com/hajimeo/samples/master/misc/k8s-nxrm3-ha-enable.sh --compressed | bash /dev/stdin "${_SHARE_DIR}" "${_NODE_MEMBERS}"']
