[global]
timeout = 5
retries = 1
trusted-host = nxrm3helmha-k8s.standalone.localdomain
index = https://admin:admin123@nxrm3helmha-k8s.standalone.localdomain/repository/pypi-group/pypi
index-url = https://admin:admin123@nxrm3helmha-k8s.standalone.localdomain/repository/pypi-group/simple/
extra-index-url = https://pypi.python.org/simple
#index = http://admin:admin123@dh1.standalone.localdomain:8081/repository/pypi-group/pypi
#index-url = http://admin:admin123@dh1.standalone.localdomain:8081/repository/pypi-group/simple/