syntax on
colorscheme pablo
"set nu
set hlsearch
set nocompatible
set wildmenu
set wildmode=list:longest,full
set directory=.,$TEMP
set shellcmdflag=-ic

match ErrorMsg /\<FATAL\>/
2match ErrorMsg /\<ERROR\>/
3match WarningMsg /\<WARN\>/