syntax on
colorscheme pablo
"set nu
set hlsearch
set magic
set nocompatible
"Use za (toggle), zO (open), zC (close), zR (open all?)
set nofoldenable
set foldmethod=indent
"TODO: I don't understand how below will be useful at this moment.
"set foldnestmax=10
"set foldlevel=2
set wildmenu
set wildmode=list:longest,full
set directory=.,$TEMP
set shellcmdflag=-ic
autocmd QuickFixCmdPost *grep* cwindow

"match ErrorMsg /\<FATAL\>/
"2match ErrorMsg /\<ERROR\>/
"3match WarningMsg /\<WARN\>/
