#!/usr/bin/env bash
#
# To download the latest script:
#   curl -OL https://github.com/hajimeo/samples/raw/master/java/btrace/btrace
#

if [ -z "$BTRACE_HOME" -o ! -d "$BTRACE_HOME" ] ; then
  # resolve links - $0 could be a link to btrace's home
  PRG="$0"
  progname=`basename "$0"`
  BTRACE_HOME=`dirname "$PRG"`
  BTRACE_HOME=`cd "$BTRACE_HOME" && pwd`
fi

[ -f "${BTRACE_HOME}/btrace-client.jar" ] || curl -sfo ${BTRACE_HOME}/btrace-client.jar -L https://raw.githubusercontent.com/hajimeo/samples/master/java/btrace/btrace-client.jar
[ -f "${BTRACE_HOME}/btrace-agent.jar" ] || curl -sfo ${BTRACE_HOME}/btrace-agent.jar -L https://raw.githubusercontent.com/hajimeo/samples/master/java/btrace/btrace-agent.jar
[ -f "${BTRACE_HOME}/btrace-boot.jar" ] || curl -sfo ${BTRACE_HOME}/btrace-boot.jar -L https://raw.githubusercontent.com/hajimeo/samples/master/java/btrace/btrace-boot.jar

if [ -f "${BTRACE_HOME}/btrace-client.jar" ] ; then
    if [ "${JAVA_HOME}" = "" ]; then
        export JAVA_HOME="$(dirname $(dirname `readlink /proc/${1}/exe`))"
    fi

    if [ "${JAVA_HOME}" != "" ]; then
       case "`uname`" in
          Darwin*)
              # In Mac OS X, tools.jar is classes.jar and is kept in a
              # different location. Check if we can locate classes.jar
              # based on ${JAVA_VERSION}
              TOOLS_JAR="/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Classes/classes.jar"

              # if we can't find, try relative path from ${JAVA_HOME}. Usually,
              # /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
              # is JAVA_HOME. (or whatever version beyond 1.6.0!)
              if [ ! -f ${TOOLS_JAR} ] ; then
                  TOOLS_JAR="${JAVA_HOME}/../Classes/classes.jar"
              fi

              # If we still can't find, tell the user to set JAVA_VERSION.
              # This way, we can avoid zip file errors from the agent side
              # and "connection refused" message from client.
              if [ ! -f ${TOOLS_JAR} ] ; then
                  echo "Please set JAVA_VERSION to the target java version"
                  exit 1
              fi
          ;;
          *)
              TOOLS_JAR="${JAVA_HOME}/lib/tools.jar"
          ;;
       esac

       if [ ! -r "${TOOLS_JAR}" ]; then
          echo "No ${TOOLS_JAR}. OpenJDK 11 may not be supported yet: https://github.com/btraceio/btrace/issues/374"
          exit 1
       fi

       # What is dtrace.jar?
       ${JAVA_HOME}/bin/java -cp "${BTRACE_HOME}/btrace-client.jar":${TOOLS_JAR}:/usr/share/lib/java/dtrace.jar com.sun.btrace.client.Main $*
    else
       echo "Please set JAVA_HOME before running this script"
       exit 1
    fi
else
    echo "Please set BTRACE_HOME before running this script"
    exit 1
fi
