FROM ${_NXRM_HOST}nexus-iq-server:${_TAG:-"latest"}

# From v125 microdnf
RUN dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm &&
    dnf -y install postgresql12 postgresql12-server

