FROM centos:6
# HDP software requirements
RUN yum -y update
# This is temp workaround to avoid dependency error
RUN yum -y downgrade glibc-2.12-1.166.el6.x86_64 glibc-common-2.12-1.166.el6.x86_64
RUN yum -y install scp curl unzip tar wget openssl python
RUN yum -y install epel-release krb5-workstation
RUN yum -y install yum-utils sudo openssh-server openssh-clients which vim net-tools lsof tcpdump
#RUN yum -y install dnsmasq

#RUN ssh-keygen -q -t rsa -N ''
RUN mkdir -m 600 /root/.ssh
#TODO: shouldn't hardcode the private key
RUN echo -e '_REPLACE_WITH_YOUR_PRIVATE_KEY_' > /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa
RUN ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub
RUN cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
RUN chown -R root:root /root/.ssh

RUN setenforce 0 || echo ko
RUN chkconfig iptables off || systemctl disable iptables.service || echo ko
#RUN /etc/init.d/iptables stop

RUN ( grep ^PermitRootLogin /etc/ssh/sshd_config && sed -i 's/^PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config ) || echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN ( grep ^GSSAPIAuthentication /etc/ssh/sshd_config && sed -i 's/^GSSAPIAuthentication yes/GSSAPIAuthentication no/' /etc/ssh/sshd_config ) || echo 'GSSAPIAuthentication no' >> /etc/ssh/sshd_config
RUN ( grep ^UseDNS /etc/ssh/sshd_config && sed -i 's/^UseDNS yes/UseDNS no/' /etc/ssh/sshd_config ) || echo 'UseDNS no' >> /etc/ssh/sshd_config
RUN service sshd restart || systemctl restart sshd.service || echo ko

#RUN echo 'user=root' >> /etc/dnsmasq.conf
#RUN echo 'listen-address=127.0.0.1' >> /etc/dnsmasq.conf
#RUN echo 'resolv-file=/etc/resolv.dnsmasq.conf' >> /etc/dnsmasq.conf
#RUN echo 'conf-dir=/etc/dnsmasq.d' >> /etc/dnsmasq.conf
#RUN echo 'addn-hosts=/etc/banner_add_hosts' >> /etc/dnsmasq.conf
#RUN echo 'nameserver 172.17.0.1' > /etc/resolv.dnsmasq.conf
#RUN service dnsmasq restart || echo ko

RUN umask 022

RUN echo -e '#!/bin/bash\n/etc/init.d/iptables stop\n_DEF_GW="$3"\nif [ -n "$1" ]; then\n  /sbin/ifconfig eth0 $1\n  if [ -n "$_DEF_GW" ]; then  # 172.17.0.1\n    /sbin/ip route add default via $_DEF_GW dev eth0\n  fi\nfi\n\nif [ -n "$2" ]; then\n  grep  -E "^$1\s+$2" /etc/hosts || echo "$1 $2" >> /etc/hosts\n  hostname $2\nfi\nservice sshd restart || systemctl restart sshd.service || echo ko\nbash' > /startup.sh
RUN chmod a+x /startup.sh

