FROM ${_NXRM_HOST}nexus-iq-server:${_TAG:-"latest"}

# From v125 microdnf
RUN dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm &&
    dnf -y install postgresql12 postgresql12-server

# TODO: probably works
RUN dnf install -y openssh-server
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''
#ADD src/sshd/sshd_config /etc/ssh/sshd_config
RUN echo root:admin123 | chpasswd