FROM centos:7.6.1810

# Install software/tools used by nexus users
RUN yum install -y sudo bind-utils net-tools scp curl unzip tar wget openssl which file vim strace lsof tcpdump openssh-server openssh-clients openldap-clients nc rsync file python
# Below line installs client tools, but as this is for testing Nexus, not installing in the Dockerfile.
#python3 maven rubygems && yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo && yum install -y ripgrep && curl -sL https://rpm.nodesource.com/setup_10.x | bash - && yum install -y nodejs && npm install yarn -g && rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm && yum install -y aspnetcore-runtime-3.1 && pip3 install conan && yum install -y epel-release && yum install -y golang

# Disable iptables and SeLinux, setup ssh (replace "_REPLACE_WITH_YOUR_PRIVATE_KEY_")
RUN setenforce 0 || echo ko;\
systemctl disable firewalld.service || echo ko;\
mkdir -m 600 /root/.ssh;\
echo -e '_REPLACE_WITH_YOUR_PRIVATE_KEY_' > /root/.ssh/id_rsa;\
chmod 400 /root/.ssh/id_rsa;\
ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub;\
cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys;\
chmod 600 /root/.ssh/authorized_keys;\
chown -R root:root /root/.ssh;\
( grep ^PermitRootLogin /etc/ssh/sshd_config && sed -i 's/^PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config ) || echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config;\
( grep ^GSSAPIAuthentication /etc/ssh/sshd_config && sed -i 's/^GSSAPIAuthentication yes/GSSAPIAuthentication no/' /etc/ssh/sshd_config ) || echo 'GSSAPIAuthentication no' >> /etc/ssh/sshd_config;\
( grep ^UsePAM /etc/ssh/sshd_config && sed -i 's/^UsePAM yes/UsePAM no/' /etc/ssh/sshd_config ) || echo 'UsePAM no' >> /etc/ssh/sshd_config;\
( grep ^UseDNS /etc/ssh/sshd_config && sed -i 's/^UseDNS yes/UseDNS no/' /etc/ssh/sshd_config ) || echo 'UseDNS no' >> /etc/ssh/sshd_config;\
umask 022

# Centos 7 customizations, by default leave only sshd enabled
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;\
systemctl enable sshd;

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]