# https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-ha-helm
# https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability/high-availability-deployment-options/option-2---on-premises-high-availability-deployment-using-kubernetes#Option2OnPremisesHighAvailabilityDeploymentUsingKubernetes-helmlic

# LIMITATION:
#   Can't (or need to be careful) use special characters such as double-quotes and dollar mark.

#$ export HELM_NAME="sonatype-helm" NAME_SPACE="nexusrepo" RELEASE_NAME="nxrm3ha" ADMIN_PWD="admin123" LICENSE_B64="$(base64 -i $HOME/share/sonatype/sonatype-license.lic)" DB_SERVER="192.168.4.31";export NFS_SERVER="192.168.4.31" SHARE_DIR="/var/tmp/share/sonatype/${RELEASE_NAME}-nfs"

# Most likely only once
#$ helm repo add ${HELM_NAME} https://sonatype.github.io/helm3-charts/
#$ helm search repo ${HELM_NAME}/nxrm-ha --versions | head
#$ #kubectl create namespace ${NAME_SPACE}
# Setting up NFS PV and PVC (used in `additionalVolumes`)
#$ eval "echo \"$(cat ./k8s-nfs-pv-pvc-tmpl.yaml | grep -v '^\s*#')\"" > ./${RELEASE_NAME}-nfs-pv-pvc.yaml
#$ kubectl apply -f ./${RELEASE_NAME}-nfs-pv-pvc.yaml -n ${NAME_SPACE}

# Install / reinstall / upgrade
#$ helm repo update ${HELM_NAME}
#$ #helm uninstall ${RELEASE_NAME} -n ${NAME_SPACE}
#$ eval "echo \"$(cat ./helm-nxrm3ha-values.yml | grep -v '^\s*#')\"" > ./${RELEASE_NAME}_values.yaml
#$ helm upgrade -i ${RELEASE_NAME} ${HELM_NAME}/nxrm-ha -f ./${RELEASE_NAME}_values.yaml -n ${NAME_SPACE} --debug # --version 65.0.0 --dry-run

# For troubleshooting
#$ git -C ~/IdeaProjects/nxrm3-ha-repository pull && git -C ~/IdeaProjects/nxrm3-ha-repository fetch
#$ helm upgrade ${RELEASE_NAME} ~/IdeaProjects/nxrm3-ha-repository/nxrm-ha -f ./${RELEASE_NAME}_values.yaml --dry-run > ${RELEASE_NAME}_dry-run.yaml

#$ helm template nxrm3ha sonatype-helm/nxrm-ha -f ./helm-nxrm3ha-values.yml -n sonatype-helm >./helm-nxrm3ha-deploying.yaml
#$ kubectl -n sonatype-helm apply -f ./helm-nxrm3ha-deploying.yaml

# Seems broken?
namespaces:
  nexusNs:
    enabled: false
    name: ${NAME_SPACE}

statefulset:
  name: nxrm-statefulset
  serviceName: nxrm-statefulset-service
  replicaCount: 1
  clustered: true
  additionalVolumeMounts:
    - name: nexus-blobs-volume
      mountPath: /nexus-data/blobs
  additionalVolumes:
    - name: nexus-blobs-volume
      persistentVolumeClaim:
        claimName: ${RELEASE_NAME}-nfs-pv-claim
  container:
    image:
      repository: sonatype/nexus3
      tag: latest
    resources:
      # See help documentation, these are minimum system requirements
      requests:
        cpu: 1
        memory: '3Gi'
      limits:
        cpu: 2
        memory: '4Gi'
    containerPort: 8081
    pullPolicy: IfNotPresent
    terminationGracePeriod: 120
    env:
      nexusDBName: nxrm3helmha
      nexusDBPort: 5432
      install4jAddVmParams: '-Xms1024m -Xmx2703m -Dnexus.scripts.allowCreation=true -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.rmi.port=9000 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=true -Djava.rmi.server.hostname=127.0.0.1'
      jdbcUrlParams: null # Must start with a '?' e.g. '?foo=bar&baz=foo'
  livenessProbe:
    failureThreshold: 6
    initialDelaySeconds: 120
    path: /
    periodSeconds: 60
  readinessProbe:
    failureThreshold: 6
    initialDelaySeconds: 120
    path: /
    periodSeconds: 60
  imagePullSecrets: {}

service:  #Nexus Repo NodePort Service
  nexus:
    enabled: true
    # TODO: The name seems stopped working from 3.63?
    #name: 'nexus-service'
    type: NodePort
    protocol: TCP
    port: 8081
    targetPort: 8081
  docker:  #Nodeport Service for Docker Service
    #name: 'nexus-docker-service'
    enabled: true
    type: NodePort
    protocol: TCP
    port: 4999
    targetPort: 4999

secret:
  secretProviderClass: 'secretProviderClass'
  provider: provider # e.g. aws, azure etc
  dbSecret:
    name: 'nxrm-db-secret'
    enabled: true
  db:
    user: 'nxrm3ha'
    userAlias: nxrm-db-user-alias
    password: 'nxrm3ha'
    passwordAlias: nxrm-db-password-alias
    host: '${DB_SERVER}'
    hostAlias: nxrm-db-host-alias
  nexusAdmin:
    name: 'nexusAdminPassword'
    alias: 'admin-nxrm-password-alias'
  nexusAdminSecret:
    enabled: true
    adminPassword: '${ADMIN_PWD}'
  license:
    name: nexus-repo-license.lic
    licenseSecret:
      enabled: true
      fileContentsBase64: '${LICENSE_B64}'
      mountPath: /var/nexus-repo-license