# To check the deploy-ing yaml file (basically same as --dry-run)
#$ helm template nxiqha sonatype/nexus-iq-server-ha -f ./helm-nxiqha-values.yml -n sonatype-ha >./helm-nxiqha-deploying.yaml

# To re-install (not from scratch as persistent volumes 'iq-server-pv' remain)
#$ helm uninstall nxiqha -n sonatype-ha
#$ helm install nxiqha sonatype/nexus-iq-server-ha -f ./helm-nxiqha-values.yml --set-file iq_server.license=$HOME/share/sonatype/sonatype-license.lic -n sonatype-ha

# To upgrade:
#$ helm repo update sonatype
#$ helm search repo sonatype/nexus-iq-server-ha --versions | head
#$ helm upgrade nxiqha sonatype/nexus-iq-server-ha -f ./helm-nxiqha-values.yml -n sonatype-ha #--dry-run

# Installing from github (eg: older versions due to CLM-28041)
#$ git -C ~/IdeaProjects/nexus-iq-server-ha pull && git -C ~/IdeaProjects/nexus-iq-server-ha fetch
#$ helm upgrade --install nxiqha ~/IdeaProjects/nexus-iq-server-ha/chart -f ~/IdeaProjects/samples/kubernetes/helm-nxiqha-values.yml -n sonatype-ha #--version 1.162.0 --dry-run
# NOTE --version uses CHART VERSION not APP VERSION

iq_server:
  # '--set global.imageRegistry=MY_NXRM' can be used too
  imageRegistry: # Container image registry, if not specified the Docker public registry will be used
  image: "sonatype/nexus-iq-server"
  tag: "latest"
  imagePullPolicy: "Always" # Default "IfNotPresent", and "Always" fails with this helm chart
  javaOpts: "-Xms2g -Xmx4g -XX:+UseG1GC -XX:ActiveProcessorCount=2"
  # TODO: doesn't work: -XX:+LogVMOutput -XX:LogFile=/sonatype-work/clm-cluster/log/jvm.log
  # -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintClassHistogramAfterFullGC -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Xloggc:/sonatype-work/clm-cluster/log/gc.%t.log
  #It seems -Djava.util.prefs.userRoot=/sonatype-work/javaprefs is no longer required?
  database:
    hostname: "192.168.4.31"
    port: 5432
    name: "iqha"
    username: "iqha"
    password: "iqha"
  persistence:
    persistentVolumeName: "iq-server-pv"
    persistentVolumeClaimName: "iq-server-pvc"
    persistentVolumeRetainPolicy: "keep"
    persistentVolumeClaimRetainPolicy: "keep"
    size: "1Gi"
    accessModes:
      - ReadWriteMany
    nfs:
      server: "192.168.4.31"
      path: "/var/tmp/share/sonatype/nxiqha"
  replicas: 1
  # Assuming the ID stays same (1000). TODO: not sure if clm-server dir is visible.
  pvOwnershipOverride:  "find /sonatype-work/clm-cluster -mindepth 1 -maxdepth 3 -type d ! -user 1000 | xargs -P3 -I{} -t chown 1000:1000 {}"

# Load balancer (not using ingress)
ingress:
  enabled: false
ingress-nginx:
  enabled: false