statefulset:
  # This is not supported
  enabled: false
replicaCount: 1
image:
  # TODO: Sonatype Official Public Image or specify NXRM3 one
  repository: sonatype/nexus-iq-server
  tag: 1.114.0
  pullPolicy: IfNotPresent

iq:
  name: nxiq
  hostname: nxiq-k8s.standalone.localdomain
  applicationPort: 8070
  adminPort: 8071
  memory: 1Gi
  # base 64 encoded license file with no line breaks
  licenseSecret: ""
  # add this line with this file path and the `licenseSecret` above to autoconfigure licensing
  # licenseFile: /etc/nexus-iq-license/license_lic
  extraLabels:
  # add the following two lines to mount a secrets volume within the container at the specified location
  secretName: #secret-jks
  secretMountName: #/etc/secret-volume
  env:
    - name: JAVA_OPTS
      value: "-Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs"

# In conjunction with 'secretName' and 'secretMountName' above, this is an example of how to inject required password
# secrets into the runtime environment, and how to modify the startup of the server to utilize custom Java SSL stores.
#    - name: TRUSTSTORE_PASSWORD
#        valueFrom:
#          secretKeyRef:
#            name: secret-jks
#            key: truststorePassword
#    - name: KEYSTORE_PASSWORD
#      valueFrom:
#        secretKeyRef:
#          name: secret-jks
#          key: keystorePassword
#    - name: JAVA_OPTS
#      value: "-Djavax.net.ssl.keyStoreType=jks -Djavax.net.ssl.keyStore=/etc/secret-volume/keystore.jks -Djavax.net.ssl.keyStorePassword=$(KEYSTORE_PASSWORD) -Djavax.net.ssl.trustStoreType=jks -Djavax.net.ssl.trustStore=/etc/secret-volume/truststore.jks -Djavax.net.ssl.trustStorePassword=$(TRUSTSTORE_PASSWORD) -Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs"


deploymentStrategy: Recreate
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# ./start.sh: line2: /var/log/nexus-iq-server/stderr.log: Permission denied
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: "ClusterIP"
  port: 80

ingress:
  enabled: false
  annotations: {kubernetes.io/ingress.class: nginx}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # TODO: do not want to use static hostnames
  hostUI: nxiq-k8s.standalone.localdomain
  hostUIPath: /
  hostAdmin: nxiq-admin-k8s.standalone.localdomain
  hostAdminPath: /

  tls: []
    # - secretName: nexus-local-tls
    #   hosts:
    #     - iqserver.local
    #     - admin.iqserver.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 1Gi

configYaml:
  baseUrl: http://nxiq-k8s.standalone.localdomain:8070
  sonatypeWork: /sonatype-work
  #TODO: licenseFile:
  server:
    applicationConnectors:
      - type: http
        port: 8070
    adminConnectors:
      - type: http
        port: 8071
    # HTTP request log settings.
    requestLog:
      appenders:
        #All appenders set to console
        - type: file
          currentLogFilename: /var/log/nexus-iq-server/request.log
          logFormat: "%clientHost %l %user [%date] \"%requestURL\" %statusCode %bytesSent %elapsedTime \"%header{User-Agent}\""
          archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
          archivedFileCount: 10

  createSampleData: true
  enableDefaultPasswordWarning: false

  logging:
    # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
    level: DEBUG

    # Logger-specific settings.
    loggers:
      "com.sonatype.insight.scan": INFO
      "eu.medsea.mimeutil.MimeUtil2": INFO
      "org.apache.http": INFO
      "org.apache.http.wire": ERROR
      "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
      "org.eclipse.jetty": INFO
      "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO   # WARNING: This reveals credentials at DEBUG level
      "com.sonatype.insight.audit":
        appenders:
        - type: file
          currentLogFilename: /var/log/nexus-iq-server/audit.log
          archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
          archivedFileCount: 10
      #"com.sonatype.insight.policy.violation":
      #  appenders:
      #    - type: console
      #      # Do not display log statements below this threshold to stdout.
      #      threshold: INFO

    appenders:
      - type: console
        threshold: INFO
        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
      - type: file
        threshold: ALL
        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
        currentLogFilename: /var/log/nexus-iq-server/clm-server.log
        archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
        archivedFileCount: 10

  # TODO: database:
  #  type: postgresql
  #  hostname: postgres.k8s.standalone.localdomain
  #  port: 5432
  #  name: sonatype
  #  username: sonatype
  #  password: ********