# https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-ha-helm
# https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability/high-availability-deployment-options/option-2---on-premises-high-availability-deployment-using-kubernetes#Option2OnPremisesHighAvailabilityDeploymentUsingKubernetes-helmlic

# LIMITATION:
#   Can't (or need to be careful) use special characters such as double-quotes and dollar mark.

#$ helm repo add sonatype-helm https://sonatype.github.io/helm3-charts/
#$ kubectl -n sonatype-helm create secret generic sonatype-license --from-file sonatype-license.lic=/var/tmp/share/sonatype/sonatype-license.lic

#$ NAME_SPACE="sonatype-helm" RELEASE_NAME="nxrm3ha"
#$ LICENSE_B64="$(base64 -i /var/tmp/share/sonatype/sonatype-license.lic)"
#$ eval "echo \"$(cat ./helm-nxrm3ha-values.yml | grep -v '^\s*#')\"" > ./${RELEASE_NAME}.yaml
#$ helm install ${RELEASE_NAME} ${NAME_SPACE}/nxrm-ha -f ./${RELEASE_NAME}.yaml --debug #--dry-run

# For troubleshooting
#$ helm template nxrm3ha sonatype-helm/nxrm-ha -f ./helm-nxrm3ha-values.yml -n sonatype-helm >./helm-nxrm3ha-deploying.yaml
#$ kubectl -n sonatype-helm apply -f ./helm-nxrm3ha-deploying.yaml

namespaces:
  nexusNs: ${NAME_SPACE}  # Why need namespace???
statefulset:
  name: nxrm-statefulset
  serviceName: nxrm-statefulset-service
  replicaCount: 1
  initContainer:
    image:
      repository: busybox
      tag: 1.33.1
    resources:
      limits:
        cpu: '0.2'
        memory: '512Mi'
      requests:
        cpu: '0.1'
        memory: '256Mi'
  container:
    image:
      repository: sonatype/nexus3
      tag: latest
    resources:
      # See help documentation, these are minimum system requirements
      requests:
        cpu: 1
        memory: '6Gi'
      limits:
        cpu: 2
        memory: '8Gi'
    containerPort: 8081
    pullPolicy: IfNotPresent
    terminationGracePeriod: 120
    env:
      nexusDBName: nxrm3helmha
      nexusDBPort: 5432
      install4jAddVmParams: '-Xms2703m -Xmx2703m'
      jdbcUrlParams: null # Must start with a '?' e.g. '?foo=bar&baz=foo'
  requestLogContainer:
    image:
      repository: busybox
      tag: 1.33.1
    resources:
      limits:
        cpu: '0.2'
        memory: '512Mi'
      requests:
        cpu: '0.1'
        memory: '256Mi'
  auditLogContainer:
    image:
      repository: busybox
      tag: 1.33.1
    resources:
      limits:
        cpu: '0.2'
        memory: '512Mi'
      requests:
        cpu: '0.1'
        memory: '256Mi'
  taskLogContainer:
    image:
      repository: busybox
      tag: 1.33.1
    resources:
      limits:
        cpu: '0.2'
        memory: '512Mi'
      requests:
        cpu: '0.1'
        memory: '256Mi'
  livenessProbe:
    failureThreshold: 6
    initialDelaySeconds: 120
    path: /
    periodSeconds: 60
  readinessProbe:
    failureThreshold: 6
    initialDelaySeconds: 120
    path: /
    periodSeconds: 60
  imagePullSecrets: {}

secret:
  secretProviderClass: 'secretProviderClass'
  provider: provider # e.g. aws, azure etc
  dbSecret:
    name: 'nxrm-db-secret'
    enabled: true
  db:
    user: 'nxrm3ha'
    userAlias: nxrm-db-user-alias
    password: 'nxrm3ha'
    passwordAlias: nxrm-db-password-alias
    host: '192.168.1.31'  # Why port is hard-coded, 5432
    hostAlias: nxrm-db-host-alias
  nexusAdmin:
    name: 'nexusAdminPassword'
    alias: 'admin-nxrm-password-alias'
  nexusAdminSecret:
    enabled: true
    adminPassword: admin123
  license:
    name: nexus-repo-license.lic
    licenseSecret:
      enabled: true
      fileContentsBase64: '${LICENSE_B64}'
      mountPath: /var/nexus-repo-license