# Upgrading IQ may require longer probe timeouts
#kubectl patch deployment -n sonatype nxiq-nexus-iq-server --patch-file ./k8s-iq-probe-patch.yaml
spec:
  template:
    spec:
      containers:
        - name: nexus-iq-server
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 120
            successThreshold: 1
            failureThreshold: 6
            timeoutSeconds: 10
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 60
            timeoutSeconds: 10
