# IQ upgrading to v118 or higher may fail due to the UID change.
#   ./start.sh: line2: /var/log/nexus-iq-server/stderr.log: Permission denied
# kubectl patch deployment -n ${namespace} ${deployment-name} --patch-file ./k8s-iq-uid-patch.yaml
# TODO: Could not workaround with 'runAsUser: 1000' or 'fsGroup: 1000', or even below as patch doesn't work with initContainers
spec:
  # https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  initContainers:
    - name: update-uid-patch
      image: busybox:1.28
      command: ['sh', '-c', "chown -v -R 1000:1000 /var/log/nexus-iq-server /sonatype-work"]
      volumeMounts:
        - name: nxiq-pv-data
          mountPath: /sonatype-work
        - name: nxiq-pv-log
          mountPath: /var/log/nexus-iq-server