# kubectl apply -n sonatype -f k8s-nexus-ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
spec:
  rules:
    # NXRM3 + PostgreSQL standalone
    - host: nxrm3-pg-k8s.standalone.localdomain
      http:
        paths:
          - backend:
              service:
                name: nxrm3-pg-service
                port:
                  number: 8081
            pathType: Prefix
            path: /
    - host: docker-k8s.standalone.localdomain
      http:
        paths:
          - backend:
              service:
                name: nxrm3-pg-service
                port:
                  number: 5000
            pathType: Prefix
            path: /

    # IQ
    - host: nxiq-k8s.standalone.localdomain
      http:
        paths:
          - backend:
              service:
                name: nxiq-nexus-iq-server
                port:
                  number: 8070
            pathType: Prefix
            path: /
    # NOTE: Do i need to expose this?
    - host: nxiq-admin-k8s.standalone.localdomain
      http:
        paths:
          - backend:
              service:
                name: nxiq-nexus-iq-server
                port:
                  number: 8071
            pathType: Prefix
            path: /
